### ISSUE TITLE
 Analysis page crash - "Trello::Error: could not find list for card"

### ISSUE THREAD

**Issue by larryprice** [ollert/ollert#64]
User found a crash where one of her boards won't load. I've attached the relevant log.

[ollert.log](https://github.com/ollert/ollert/files/1676243/ollert.log)

**Comment by larryprice** [comment]
I'm fairly certain I've narrowed it down to when we fetch labels and look for only "open" cards (see: [label_count_fetcher.rb](https://github.com/ollert/ollert/blob/master/utils/fetchers/label_count_fetcher.rb)). After executing `client.get("/boards/:boardId/cards/open", actions: 'createCard,convertToCardFromCheckItem,moveCardToBoard', limit: 1000)` from the `irb` with the corresponding creds, I get the error:

``` ruby
E, [2018-01-29T20:55:03.227457 #4302] ERROR -- : [400 GET https://api.trello.com/1/boards/:boardId/cards/open?actions=createCard%2CconvertToCardFromCheckItem%2CmoveCardToBoard&limit=1000]: could not find list for card
Trello::Error: could not find list for card
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/ruby-trello-2.0.0/lib/trello/client.rb:99:in `invoke_verb'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/ruby-trello-2.0.0/lib/trello/client.rb:19:in `get'
	from (irb):43
	from /home/lrp/Projects/2018/ollert/Rakefile:33:in `block in <top (required)>'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
	from /home/lrp/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/bin/rake:22:in `load'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/bin/rake:22:in `<main>'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/bin/ruby_executable_hooks:15:in `eval'
	from /home/lrp/.rvm/gems/ruby-2.4.0@ollert/bin/ruby_executable_hooks:15:in `<main>'
```

However, everything works fine when I use the `visible` endpoint instead of the `open` endpoint. __WEIRD__. Seems like we should have been using the `visible` endpoint anyway? That's my proposed fix.
